# Generated by Django 3.1.5 on 2021-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Файл')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('width', models.IntegerField(blank=True, default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, default=0, verbose_name='Высота')),
                ('changed_image_file', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
